# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    admin_default_email: 'admin@admin.com'
    env(BOOKS_PER_PAGE): 10
    omdb_base_uri: 'http://www.omdbapi.com'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            int $booksPerPage: '%env(int:BOOKS_PER_PAGE)%'
            string $sfVersion: '%env(key:require:key:symfony:key:extra:json:file:resolve:COMPOSER_PATH)%'
    _instanceof:
        App\Notifier\Factory\IterableFactoryInterface:
            tags:
                - { name: app.notification_factory }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Notifier\Factory\ChainNotificationFactory:
        arguments:
            $factories: !tagged_iterator {tag: 'app.notification_factory', default_index_method: 'getDefaultIndexName'}
